#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ICT638June2020Grou2Android2.Resource", IsApplication=true)]

namespace ICT638June2020Grou2Android2
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int abc_fade_in = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int abc_fade_out = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int abc_grow_fade_in_from_bottom = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int abc_popup_enter = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int abc_popup_exit = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int abc_shrink_fade_out_from_bottom = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int abc_slide_in_bottom = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int abc_slide_in_top = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int abc_slide_out_bottom = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int abc_slide_out_top = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int abc_tooltip_enter = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int abc_tooltip_exit = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int design_bottom_sheet_slide_in = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int design_bottom_sheet_slide_out = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int design_snackbar_in = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int design_snackbar_out = 2130771983;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int design_appbar_state_list_animator = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int design_fab_hide_motion_spec = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int design_fab_show_motion_spec = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int mtrl_btn_state_list_anim = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int mtrl_btn_unelevated_state_list_anim = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int mtrl_chip_state_list_anim = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int mtrl_fab_hide_motion_spec = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int mtrl_fab_show_motion_spec = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int mtrl_fab_transformation_sheet_collapse_spec = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int mtrl_fab_transformation_sheet_expand_spec = 2130837513;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			// aapt resource value: 0x7F0800DB
			public const int tvUserLName = 2131230939;
			
			// aapt resource value: 0x7F0800E1
			public const int tvUserpass = 2131230945;
			
			// aapt resource value: 0x7F0800DC
			public const int tvUserPassword = 2131230940;
			
			// aapt resource value: 0x7F0800E2
			public const int tvUserpassword = 2131230946;
			
			// aapt resource value: 0x7F0800E3
			public const int tvUserphon = 2131230947;
			
			// aapt resource value: 0x7F0800DD
			public const int tvUserPnumber = 2131230941;
			
			// aapt resource value: 0x7F0800E4
			public const int tvUseruniq = 2131230948;
			
			// aapt resource value: 0x7F0800DE
			public const int tvUserUsername = 2131230942;
			
			// aapt resource value: 0x7F0800E5
			public const int uniform = 2131230949;
			
			// aapt resource value: 0x7F0800E6
			public const int unlabeled = 2131230950;
			
			// aapt resource value: 0x7F0800E7
			public const int up = 2131230951;
			
			// aapt resource value: 0x7F0800E8
			public const int useLogo = 2131230952;
			
			// aapt resource value: 0x7F0800E9
			public const int view_offset_helper = 2131230953;
			
			// aapt resource value: 0x7F0800EA
			public const int visible = 2131230954;
			
			// aapt resource value: 0x7F0800EB
			public const int wide = 2131230955;
			
			// aapt resource value: 0x7F0800EC
			public const int withText = 2131230956;
			
			// aapt resource value: 0x7F0800ED
			public const int wrap_content = 2131230957;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int abc_config_activityDefaultDur = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int abc_config_activityShortDur = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int app_bar_elevation_anim_duration = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int bottom_sheet_slide_duration = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int cancel_button_image_alpha = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int config_tooltipAnimTime = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int design_snackbar_text_max_lines = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int design_tab_indicator_anim_duration_ms = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int hide_password_duration = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int mtrl_btn_anim_delay_ms = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int mtrl_btn_anim_duration_ms = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int mtrl_chip_anim_duration = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int mtrl_tab_indicator_anim_duration_ms = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int show_password_duration = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int status_bar_notification_info_maxnum = 2131296270;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F0B0032
			public const int notification_media_action = 2131427378;
			
			// aapt resource value: 0x7F0B0033
			public const int notification_media_cancel_action = 2131427379;
			
			// aapt resource value: 0x7F0B0034
			public const int notification_template_big_media = 2131427380;
			
			// aapt resource value: 0x7F0B0035
			public const int notification_template_big_media_custom = 2131427381;
			
			// aapt resource value: 0x7F0B0036
			public const int notification_template_big_media_narrow = 2131427382;
			
			// aapt resource value: 0x7F0B0037
			public const int notification_template_big_media_narrow_custom = 2131427383;
			
			// aapt resource value: 0x7F0B0038
			public const int notification_template_custom_big = 2131427384;
			
			// aapt resource value: 0x7F0B0039
			public const int notification_template_icon_group = 2131427385;
			
			// aapt resource value: 0x7F0B003A
			public const int notification_template_lines_media = 2131427386;
			
			// aapt resource value: 0x7F0B003B
			public const int notification_template_media = 2131427387;
			
			// aapt resource value: 0x7F0B003C
			public const int notification_template_media_custom = 2131427388;
			
			// aapt resource value: 0x7F0B003D
			public const int notification_template_part_chronometer = 2131427389;
			
			// aapt resource value: 0x7F0B003E
			public const int notification_template_part_time = 2131427390;
			
			// aapt resource value: 0x7F0B003F
			public const int register_layout = 2131427391;
			
			// aapt resource value: 0x7F0B0040
			public const int select_dialog_item_material = 2131427392;
			
			// aapt resource value: 0x7F0B0041
			public const int select_dialog_multichoice_material = 2131427393;
			
			// aapt resource value: 0x7F0B0042
			public const int select_dialog_singlechoice_material = 2131427394;
			
			// aapt resource value: 0x7F0B0043
			public const int support_simple_spinner_dropdown_item = 2131427395;
			
			// aapt resource value: 0x7F0B0044
			public const int user_layout = 2131427396;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7F0C0001
			public const int ic_launcher_foreground = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int ic_launcher_round = 2131492866;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7F0D0010
			public const int abc_font_family_headline_material = 2131558416;
			
			// aapt resource value: 0x7F0D0011
			public const int abc_font_family_menu_material = 2131558417;
			
			// aapt resource value: 0x7F0D0012
			public const int abc_font_family_subhead_material = 2131558418;
			
			// aapt resource value: 0x7F0D0013
			public const int abc_font_family_title_material = 2131558419;
			
			// aapt resource value: 0x7F0D0014
			public const int abc_menu_alt_shortcut_label = 2131558420;
			
			// aapt resource value: 0x7F0D0015
			public const int abc_menu_ctrl_shortcut_label = 2131558421;
			
			// aapt resource value: 0x7F0D0016
			public const int abc_menu_delete_shortcut_label = 2131558422;
			
			// aapt resource value: 0x7F0D0017
			public const int abc_menu_enter_shortcut_label = 2131558423;
			
			// aapt resource value: 0x7F0D0018
			public const int abc_menu_function_shortcut_label = 2131558424;
			
			// aapt resource value: 0x7F0D0019
			public const int abc_menu_meta_shortcut_label = 2131558425;
			
			// aapt resource value: 0x7F0D001A
			public const int abc_menu_shift_shortcut_label = 2131558426;
			
			// aapt resource value: 0x7F0D001B
			public const int abc_menu_space_shortcut_label = 2131558427;
			
			// aapt resource value: 0x7F0D001C
			public const int abc_menu_sym_shortcut_label = 2131558428;
			
			// aapt resource value: 0x7F0D001D
			public const int abc_prepend_shortcut_label = 2131558429;
			
			// aapt resource value: 0x7F0D001F
			public const int abc_searchview_description_clear = 2131558431;
			
			// aapt resource value: 0x7F0D0020
			public const int abc_searchview_description_query = 2131558432;
			
			// aapt resource value: 0x7F0D0021
			public const int abc_searchview_description_search = 2131558433;
			
			// aapt resource value: 0x7F0D0022
			public const int abc_searchview_description_submit = 2131558434;
			
			// aapt resource value: 0x7F0D0023
			public const int abc_searchview_description_voice = 2131558435;
			
			// aapt resource value: 0x7F0D001E
			public const int abc_search_hint = 2131558430;
			
			// aapt resource value: 0x7F0D0024
			public const int abc_shareactionprovider_share_with = 2131558436;
			
			// aapt resource value: 0x7F0D0025
			public const int abc_shareactionprovider_share_with_application = 2131558437;
			
			// aapt resource value: 0x7F0D0026
			public const int abc_toolbar_collapse_description = 2131558438;
			
			// aapt resource value: 0x7F0D0027
			public const int action_settings = 2131558439;
			
			// aapt resource value: 0x7F0D0029
			public const int appbar_scrolling_view_behavior = 2131558441;
			
			// aapt resource value: 0x7F0D0028
			public const int app_name = 2131558440;
			
			// aapt resource value: 0x7F0D002A
			public const int bottom_sheet_behavior = 2131558442;
			
			// aapt resource value: 0x7F0D002B
			public const int character_counter_content_description = 2131558443;
			
			// aapt resource value: 0x7F0D002C
			public const int character_counter_pattern = 2131558444;
			
			// aapt resource value: 0x7F0D002D
			public const int fab_transformation_scrim_behavior = 2131558445;
			
			// aapt resource value: 0x7F0D002E
			public const int fab_transformation_sheet_behavior = 2131558446;
			
			// aapt resource value: 0x7F0D002F
			public const int hide_bottom_view_on_scroll_behavior = 2131558447;
			
			// aapt resource value: 0x7F0D0030
			public const int mtrl_chip_close_icon_content_description = 2131558448;
			
			// aapt resource value: 0x7F0D0031
			public const int password_toggle_content_description = 2131558449;
			
			// aapt resource value: 0x7F0D0032
			public const int path_password_eye = 2131558450;
			
			// aapt resource value: 0x7F0D0033
			public const int path_password_eye_mask_strike_through = 2131558451;
			
			// aapt resource value: 0x7F0D0034
			public const int path_password_eye_mask_visible = 2131558452;
			
			// aapt resource value: 0x7F0D0035
			public const int path_password_strike_through = 2131558453;
			
			// aapt resource value: 0x7F0D0036
			public const int search_menu_title = 2131558454;
			
			// aapt resource value: 0x7F0D0037
			public const int status_bar_notification_info_overflow = 2131558455;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
